import assert from "node:assert/strict"; import { readFileSync } from "node:fs"; import test from "node:test";
const sql=readFileSync("supabase/migrations/202608020001_ads_bin_cleaning_foundation.sql","utf8");
test("RLS is enabled on every application table",()=>{const tables=[...sql.matchAll(/create table public\.(\w+)/g)].map(x=>x[1]);const rls=sql.match(/array\[([\s\S]*?)\] loop/)?.[1]??"";for(const table of tables)assert.match(rls,new RegExp(`'${table}'`),`${table} missing RLS`)});
test("customer data isolation is database-enforced",()=>{assert.match(sql,/customer_own_read/);assert.match(sql,/user_id=auth\.uid\(\)/);assert.match(sql,/address_customer_read/)});
test("technician route access is assignment-scoped",()=>{assert.match(sql,/route_tech_read[\s\S]*technician_id=auth\.uid\(\)/);assert.match(sql,/stops_tech_read[\s\S]*r\.technician_id=auth\.uid\(\)/)});
test("financial catalog changes are administrator only",()=>assert.match(sql,/catalog_versions_admin_manage[\s\S]*has_role\('administrator'\)/));
test("visit completion is protected by database trigger",()=>{for(const requirement of ["kind='before'","kind='after'","cleaning_confirmed","bins_returned","authorized_return_exception"]) assert.match(sql,new RegExp(requirement.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")))});
test("referrals reject self referral and duplicate address",()=>{assert.match(sql,/check\(referrer_customer_id <> referred_customer_id\)/);assert.match(sql,/unique\(normalized_address_hash\)/)});
test("authentication is based on Supabase auth users",()=>assert.match(sql,/references auth\.users\(id\)/));
test("portal records are customer isolated by every owner-facing policy",()=>{for(const name of ["customer_own_read","address_customer_read","bins_owner_read","subscriptions_owner_read","visits_owner_read","referrals_codes_owner","referral_credits_owner"])assert.match(sql,new RegExp(name))});
test("dispatcher is excluded from protected financial and role writes",()=>{assert.doesNotMatch(sql,/admin_staff_roles[\s\S]{0,180}dispatcher/);assert.doesNotMatch(sql,/catalog_versions_admin_manage[\s\S]{0,180}dispatcher/);assert.doesNotMatch(sql,/subscriptions_admin_manage[\s\S]{0,180}dispatcher/)});
