import Link from "next/link";
import { AppShell, Stat } from "@/components/bin-cleaning/AppShell";
import { ReferralNotifications } from "@/components/bin-cleaning/ReferralNotifications";
import { crmCustomers } from "@/lib/bin-cleaning/queries";
import { crmSignupLeads } from "@/lib/bin-cleaning/signup-queries";
import { formatCurrency } from "@/lib/bin-cleaning-plans";
import { databaseRequest } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";
const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

type PendingChange = { id:string; customer_id:string; request_type:string; requested_value:Record<string,unknown>|null; created_at:string; customers:{full_name:string}|null };
type RecentBinChange = { id:string; customer_id:string; old_trash_bin_count:number; old_recycling_bin_count:number; new_trash_bin_count:number; new_recycling_bin_count:number; old_recurring_price_cents:number|null; new_recurring_price_cents:number|null; billing_effective_policy:string; requested_at:string; customers:{full_name:string}|null };

function displayDate(value:string|null){ if(!value)return "Never"; return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/New_York"}).format(new Date(value)); }
function requestedText(value:Record<string,unknown>|null){ if(!value)return "No details supplied"; if(typeof value.value==="string")return value.value; return Object.entries(value).map(([k,v])=>`${k.replaceAll("_"," ")}: ${String(v)}`).join(" · "); }
function binSummary(t:number,r:number){ return `${t} trash + ${r} recycling`; }
function signupDiscount(lead:Awaited<ReturnType<typeof crmSignupLeads>>["leads"][number]){ if(lead.referral_code)return `Referral ${lead.referral_code}`; if(lead.promo_code)return `Promo ${lead.promo_code}`; return "None"; }
function customerEstimate(customer:Awaited<ReturnType<typeof crmCustomers>>[number],count:number){ const v=customer.subscriptions[0]?.service_plan_versions; if(!v||v.base_price_cents==null)return "Pending"; return `${formatCurrency(v.base_price_cents+Math.max(0,count-Math.max(0,v.bins_included??1))*Math.max(0,v.additional_bin_price_cents??0))} before tax`; }

export default async function CRM({searchParams}:{searchParams:{q?:string;plan?:string;status?:string;municipality?:string;pickup?:string}}){
 const [customers,signupResult,pendingChanges,recentBinChanges]=await Promise.all([
  crmCustomers(searchParams), crmSignupLeads(),
  databaseRequest<PendingChange[]>("customer_change_requests?status=eq.pending_staff_review&select=id,customer_id,request_type,requested_value,created_at,customers(full_name)&order=created_at.desc&limit=25").catch(()=>[]),
  databaseRequest<RecentBinChange[]>("customer_bin_change_requests?acknowledged_at=is.null&select=id,customer_id,old_trash_bin_count,old_recycling_bin_count,new_trash_bin_count,new_recycling_bin_count,old_recurring_price_cents,new_recurring_price_cents,billing_effective_policy,requested_at,customers(full_name)&order=requested_at.desc&limit=10").catch(()=>[])
 ]);
 const leads=signupResult.leads;
 const referralNotifications=leads.filter(l=>l.status==="submitted_unpaid"&&Boolean(l.referral_code)).map(l=>({id:l.id,customerName:l.full_name||"Incomplete name",referralCode:l.referral_code||"Referral",submittedAt:l.submitted_at||l.last_activity_at}));
 return <AppShell area="Internal CRM">
  <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-zinc-600">Customer intake, account activity, routing basics, and unpaid staging signups.</p><Link href="/bin-cleaning/crm/customers/new" className="rounded-xl bg-brand-700 px-4 py-2 font-black text-white">+ Add customer manually</Link></div>
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><Stat label="Matching test customers" value={customers.length}/><Stat label="Unverified pickup" value={customers.filter(c=>c.service_addresses.some(a=>a.trash_pickup_schedules.some(p=>p.weekday==null))).length}/><Stat label="Submitted unpaid" value={leads.filter(l=>l.status==="submitted_unpaid").length}/><Stat label="Open signup drafts" value={leads.filter(l=>l.status!=="submitted_unpaid").length}/><Stat label="Pending customer requests" value={pendingChanges.length} alert={pendingChanges.length>0}/></div>

  {pendingChanges.length>0&&<section className="card mt-6 overflow-hidden border-amber-300"><div className="flex items-center justify-between border-b p-5"><div><h2 className="text-xl font-black">Customer requests needing attention</h2><p className="text-sm text-zinc-600">These stay in permanent history after review.</p></div><Link href="/bin-cleaning/crm/activity" className="rounded-lg bg-zinc-900 px-3 py-2 text-sm font-black text-white">Open messages & notes</Link></div><div className="divide-y">{pendingChanges.slice(0,5).map(c=><div key={c.id} className="grid gap-1 p-4 md:grid-cols-[1.2fr_1fr_2fr_auto]"><Link className="font-black text-brand-700" href={`/bin-cleaning/crm/customers/${c.customer_id}`}>{c.customers?.full_name??"Customer"}</Link><span className="capitalize">{c.request_type.replaceAll("_"," ")}</span><span>Requested: <strong>{requestedText(c.requested_value)}</strong></span><span className="text-xs text-zinc-500">{displayDate(c.created_at)}</span></div>)}</div></section>}

  {recentBinChanges.length>0&&<section className="card mt-6 overflow-hidden"><div className="flex items-center justify-between border-b p-5"><div><h2 className="text-xl font-black">Recent automatic account changes</h2><p className="text-sm text-zinc-600">These stay here until acknowledged. Acknowledging clears only this notice; full history remains permanent.</p></div><Link href="/bin-cleaning/crm/activity" className="rounded-lg bg-zinc-900 px-3 py-2 text-sm font-black text-white">Open full history</Link></div><div className="divide-y">{recentBinChanges.slice(0,5).map(c=><div key={c.id} className="grid gap-2 p-4 md:grid-cols-[1.1fr_1.8fr_1fr_auto_auto] md:items-center"><Link className="font-black text-brand-700" href={`/bin-cleaning/crm/customers/${c.customer_id}`}>{c.customers?.full_name??"Customer"}</Link><span><strong>{binSummary(c.old_trash_bin_count,c.old_recycling_bin_count)}</strong> → <strong>{binSummary(c.new_trash_bin_count,c.new_recycling_bin_count)}</strong></span><span className="font-semibold">{c.old_recurring_price_cents==null||c.new_recurring_price_cents==null?"Price history saved":`${formatCurrency(c.old_recurring_price_cents)} → ${formatCurrency(c.new_recurring_price_cents)}`}<small className="block font-normal text-zinc-500">Billing: {c.billing_effective_policy.replaceAll("_"," ")}</small></span><span className="text-xs text-zinc-500">{displayDate(c.requested_at)}</span><form action="/api/bin-cleaning/crm/bin-change-acknowledge" method="post"><input type="hidden" name="request_id" value={c.id}/><button className="rounded-lg bg-brand-700 px-3 py-2 text-xs font-black text-white">Acknowledge</button></form></div>)}</div></section>}

  <ReferralNotifications referrals={referralNotifications}/>
  <section className="card mt-6 overflow-hidden"><div className="border-b p-5"><h2 className="text-xl font-black">Fictional signup pipeline</h2><p className="text-sm text-zinc-600">No signup shown here is paid or active.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead><tr>{["Customer","Status","Plan","Bins","Pickup","Discount","Estimate","Last activity"].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{leads.map(l=><tr key={l.id} className="border-t"><td className="p-3"><Link className="font-black text-brand-700" href={`/bin-cleaning/crm/signups/${l.id}`}>{l.full_name||"Incomplete name"}</Link><p className="text-xs text-zinc-500">{l.email||"No email"}</p></td><td className="p-3">{l.status.replaceAll("_"," ")}</td><td className="p-3 capitalize">{l.plan_id||"—"}</td><td className="p-3">{l.bin_count} ({l.bin_streams?.trash??0}T/{l.bin_streams?.recycling??0}R)</td><td className="p-3">{l.trash_weekday==null?"—":days[l.trash_weekday]}</td><td className="p-3">{signupDiscount(l)}</td><td className="p-3 font-bold">{l.estimated_first_charge_cents==null?"Pending":`${formatCurrency(l.estimated_first_charge_cents)} before tax`}</td><td className="p-3">{displayDate(l.last_activity_at)}</td></tr>)}</tbody></table></div></section>

  <section className="card mt-6 overflow-hidden"><div className="border-b p-5"><h2 className="text-xl font-black">Customers</h2><p className="text-sm text-zinc-600">Last activity is portal activity, not an admin view.</p></div><form className="grid gap-2 border-b p-5 sm:grid-cols-3 lg:grid-cols-6"><input name="q" defaultValue={searchParams.q} placeholder="Search name" className="rounded-lg border p-2"/><select name="plan" defaultValue={searchParams.plan}><option value="">All plans</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="twice-yearly">Twice a Year</option><option value="one-time">One-Time</option></select><select name="status" defaultValue={searchParams.status}><option value="">All statuses</option><option>active</option><option>pending_review</option></select><input name="municipality" defaultValue={searchParams.municipality} placeholder="Municipality" className="rounded-lg border p-2"/><select name="pickup" defaultValue={searchParams.pickup}><option value="">All pickup days</option>{days.map((d,i)=><option value={i} key={d}>{d}</option>)}</select><button className="rounded-lg bg-brand-700 p-2 font-bold text-white">Filter</button></form><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead><tr>{["Customer","Status","Plan","Bins","Pickup","Discount","Estimate","Last activity"].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{customers.map(c=>{const a=c.service_addresses[0];const p=a?.trash_pickup_schedules[0];const bins=(a?.bins??[]).filter(b=>b.active);const t=bins.filter(b=>b.collection_stream==="trash").length;const r=bins.filter(b=>b.collection_stream==="recycling").length;const plan=c.subscriptions[0]?.service_plan_versions.service_plans.display_name??"—";return <tr key={c.id} className="border-t"><td className="p-3"><Link className="font-black text-brand-700" href={`/bin-cleaning/crm/customers/${c.id}`}>{c.full_name}</Link><p className="text-xs text-zinc-500">{c.email}</p></td><td className="p-3">{c.account_status.replaceAll("_"," ")}</td><td className="p-3">{plan}</td><td className="p-3">{bins.length} ({t}T/{r}R)</td><td className="p-3">{p?.weekday==null?"Unverified":days[p.weekday]}</td><td className="p-3">See account</td><td className="p-3 font-bold">{customerEstimate(c,bins.length)}</td><td className="p-3"><strong>{displayDate(c.last_portal_activity_at)}</strong>{c.last_portal_login_at&&<small className="block text-zinc-500">Last login {displayDate(c.last_portal_login_at)}</small>}</td></tr>})}</tbody></table></div></section>
 </AppShell>;
}
