import type { Metadata } from "next";
import Link from "next/link";
import { BinCleaningCalculator } from "@/components/BinCleaningCalculator";
import { Container } from "@/components/Container";

export const metadata: Metadata = { title: "Signup Preview | ADS Bin Cleaning", description: "Preview the planned ADS Bin Cleaning signup experience. Signup is not yet activated.", robots: { index: false, follow: false } };
const FIELDS = ["Name", "Mobile number", "Email address", "Service address", "Trash pickup day", "Recycling information", "Designated bin-return location", "Access instructions", "Referral code"];

export default function SignupFoundationPage() {
  return <main className="bg-brand-50"><Container><div className="py-10 md:py-16"><Link href="/bin-cleaning" className="text-sm font-bold">← Back to ADS Bin Cleaning</Link><div role="status" className="mt-6 rounded-2xl border border-amber-300 bg-amber-50 p-5"><p className="font-black text-amber-950">Preview only — signup is not activated</p><p className="mt-1 text-sm text-amber-900">This visual foundation does not create accounts, save information, calculate live tax, or connect to Stripe. Please do not enter real customer information.</p></div><h1 className="mt-8 text-4xl font-black tracking-tight">ADS Bin Cleaning signup preview</h1><p className="mt-3 max-w-3xl text-zinc-700">Explore the planned responsive flow using non-sensitive sample selections only.</p>
    <section aria-labelledby="plan-heading" className="mt-10 rounded-3xl border border-zinc-200 bg-white p-4 shadow-sm sm:p-7"><h2 id="plan-heading" className="sr-only">Plan and pricing preview</h2><BinCleaningCalculator showAction={false}/></section>
    <section aria-labelledby="details-heading" className="mt-8 rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm sm:p-8"><h2 id="details-heading" className="text-2xl font-black">Planned customer details</h2><p className="mt-2 text-sm text-zinc-600">Fields are disabled to make clear that this preview cannot submit data.</p><div className="mt-6 grid gap-5 md:grid-cols-2">{FIELDS.map((field) => <label key={field} className="text-sm font-bold text-zinc-800">{field}<input disabled placeholder="Not active in this preview" className="mt-2 h-11 w-full cursor-not-allowed rounded-lg border border-zinc-300 bg-zinc-100 px-3 text-zinc-500 disabled:opacity-100" /></label>)}</div><div className="mt-6 rounded-xl bg-zinc-100 p-4 text-sm text-zinc-700"><strong>Pricing summary:</strong> The shared calculator above previews approved subtotal rules. Address validation, applicable tax, total due, account creation, and payment will be implemented in a later connected phase.</div><button disabled className="mt-6 w-full cursor-not-allowed rounded-lg bg-zinc-300 px-6 py-3 font-bold text-zinc-600 sm:w-auto">Signup not yet activated</button></section>
  </div></Container></main>;
}
